### PR TITLE
Make OpenAI provider optional

### LINKED ISSUE #134: Chat stuck when chat title creation errors
I have had an IO error when calling the 'title' model, which is used to create a chat title.

As the exception is not handled properly, the exception is raised breaking the API->UI stream.
Ideally internal errors during a chat call will not stop the stream. For the title message we might want to supress/log the error and try to create a title later in the conversation (from the first message send by the user).

### LINKED ISSUE #174: OpenAI key is needed for cron expression generator
I setup agent only with the anthropic key and I couldn't use the cron expression generator as it needs OpenAI key. Ideally, it should use the AI that is available.

### LINKED ISSUE #175: New chat defaults to GPT-4.1
I was only using the anthropic key. It is a bit annoying that each chat defaults to GPT-4.1 and I have to switch that to Claude every time. 

This also impacts the onboarding flow. The setup

Project type: Other
Key: Only anthropic

The "get initial assessment" button fails because it starts a chat with GPT-4.1 and the initial message and the key errors. Moreover, I can't recover from it by just switching the prompt and retrying as it fails with "Wait for the last response from model" (paraphrased).

Maybe a new chat should default to the model with first available key? We can also highlight that in the UI by disabling the models that don't have a key in the env.

### LINKED ISSUE #176: Chat's aren't being saved
Project type: Other
Model: Claude

The chat response is there but a reload loses all the messages from me and the agent. 

Here is a recording of what I mean: 

https://github.com/user-attachments/assets/8e5fab12-d700-47d8-afec-97c9290d8afb

### PR DESCRIPTION
**Pull request by SferaDev**
Fix #176 
Fix #175 
Fix #174 
Fix #134

### CODE REVIEW

File: apps/dbagent/src/lib/ai/providers/builtin.ts [hunk 1]
```diff
@@ -145,9 +145,18 @@ const builtinProviderModels: Record<string, Model> = (function () {
   );
 })();
 
-const defaultLanguageModel = builtinProviderModels['openai:gpt-4.1'] ?? Object.values(builtinProviderModels)[0]!;
-const defaultTitleModel = builtinProviderModels['openai:gpt-4.1-mini'] ?? Object.values(builtinProviderModels)[0]!;
-const defaultSummaryModel = builtinProviderModels['openai:gpt-4.1-mini'] ?? Object.values(builtinProviderModels)[0]!;
+const defaultLanguageModel =
+  env.OPENAI_API_KEY && builtinProviderModels['openai:gpt-4.1']
```
Comment (divyenduz) [inline apps/dbagent/src/lib/ai/providers/builtin.ts:149]: This is pretty hard to read. Maybe we can simplify this somehow?

**Review by divyenduz — APPROVED** [review]
LGTM 🚀
